clean:
	rm -rf dist
prep:
	mkdir dist
compile: prep
	gcc src/task1.c -o dist/main1.bin -g
	gcc src/task2.c -o dist/main2.bin -g
	gcc src/task3.c -o dist/main3.bin -g
	gcc src/task4.c -o dist/main4.bin -g
	gcc src/task5.c -o dist/main5.bin -g
	gcc src/task6.c -o dist/main6.bin -g
all: clean compile
